### ISSUE TITLE
Undefined binding(s) detected when compiling SELECT query

### ISSUE THREAD

**Issue by enzoqtvf** [sipcapture/homer-view-react#18]
Hey guys

I've been playing out with the react-view app, and I found out some issues when I was testing with our homer setup in Telnyx.

I was using the example, and pointing the proxy to one of our homer web app, and I was getting this error when trying to make requests:
http://localhost:9081/?from=1553629228&to=1553802028&callid=0c438bf9-65ef-4896-a5eb-a1072dc3afdd&tabs=messages,qos
`{"statusCode":503,"error":"Service Unavailable","message":"fail to get data main:Error: fail to get data fullError: Undefined binding(s) detected when compiling SELECT query: select \"id\", \"sid\", \"protocol_header\", \"data_header\", \"raw\", ROUND(EXTRACT(epoch FROM create_date)*1000) as create_date from \"hep_proto_100_default\" where \"sid\" in (?, ?) and \"create_date\" between ? and ?"}`

I've been able to reproduce on local with a fresh setup: https://github.com/enzoqtvf/homer7-docker/tree/master/heplify-server/hom7-hep-prom-graf-view
(I would be happy to open a pull request to add it to your docker examples if you guys want it)
You can run the `docker-compose up` and then open that url:
http://localhost:9081/?from=1553629228&to=1553802028&callid=0c438bf9-65ef-4896-a5eb-a1072dc3afdd&tabs=messages,qos

And check network interaction you will see a 503 coming back from the homer web app

Let me know if you guys need any other indication :)

Thanks !

**Comment by adubovikov** [comment]
we will check it ASAP

**Comment by adubovikov** [comment]
@ivanShagarov please take a look!

**Comment by lmangani** [comment]
@enzoqtvf could you kindly confirm what's on the `other side` and the version of HOMER you' re running?

**Comment by adubovikov** [comment]
I think this is because we dont have any result in this time range and of course the array of cid is empty. @ivanShagarov can you please re-check and do some asserts ?

**Comment by lmangani** [comment]
@enzoqtvf could you confirm this is the case for every query in every range, including those you surely have data for?

**Comment by lmangani** [comment]
@enzoqtvf I've just tried to spin up [this test compose](https://github.com/sipcapture/homer7-docker/blob/master/heplify-server/hom7-victoria-all/docker-compose.yml#L180) and everything works are expected. We'll need your input to reproduce your setup. Are you 100% this is querying an H7 API?

**Comment by lmangani** [comment]
@enzoqtvf any updates on this?
