### ISSUE TITLE
QOS Something went wrong

### ISSUE THREAD

**Issue by changzx** [sipcapture/homer-view-react#28]
![image](https://user-images.githubusercontent.com/42836671/64475365-97a4f700-d1b4-11e9-8963-749e06934575.png)
Something went wrong.
![image](https://user-images.githubusercontent.com/42836671/64475372-a12e5f00-d1b4-11e9-9b73-88106facef4d.png)

**Comment by lmangani** [comment]
That's correct the QoS tab is currently broken due to an API change - it should be fixed in the coming weeks.

**Comment by lmangani** [comment]
This is now fixed! Thanks for your report
