### ISSUE TITLE
Docker - Using Auth Token from Homer in Homer-view

### ISSUE THREAD

**Issue by idanam-del** [sipcapture/homer-view-react#83]
Hey,

i dont want to use the proxy but use a generated Auth Token from Homer. i the homer api accepts requests only if the token is in the header and not a prameter in the url request.

So how can i use the viewer with the auth-token?

Thank you

**Comment by lmangani** [comment]
I think this is an anti-pattern. The two authentications are equal but without the proxy everything is insecure.
We cannot support any such changes, but feel free to make a PR with any code change proposal for review.

**Comment by idanam-del** [comment]
> I think this is an anti-pattern. The two authentications are equal but without the proxy everything is insecure. We cannot support any such changes, but feel free to make a PR with any code change proposal for review.

I'm sorry but i dont understand i thought using the proxy is insecured. its says so in the github repo itself 
"This simple, primitive proxy implementation allows UNAUTHORIZED ACCESS to an HOMER 7.x API"

Either way while i use the proxy its still says login required. can i feed the proxy somehow with an auth token from homer ui?
